#!/usr/bin/env python3
"""Generate Camunda 7 Database Reference Guide (schema v7.24.0)."""
from pathlib import Path

OUT = Path(__file__).parent / "CAMUNDA_7_DATABASE_REFERENCE.md"

def T(name, cat, ch, purpose, ins, upd, delete, pk, related, rel_sum, uses, cols, rels):
    return dict(name=name, cat=cat, ch=ch, purpose=purpose, ins=ins, upd=upd, delete=delete,
                pk=pk, related=related, rel_sum=rel_sum, uses=uses, cols=cols, rels=rels)

TABLES = [
T("ACT_GE_PROPERTY","General Table",1,"Stores engine-wide configuration properties and distributed lock counters.",
  "Inserted during database initialization and when upgrades add new properties.",
  "Updated when property values or lock counters change.","Rarely deleted.","NAME_","—",
  "Standalone key-value store used internally by the process engine.",
  [("Schema Version","Stores schema.version and schema.history values."),
   ("ID Generation","Maintains next.dbid counter."),
   ("Distributed Locks","Holds deployment, startup, and cleanup locks.")],
  [("NAME_","VARCHAR(64)","Property key identifier used as the primary key."),
   ("VALUE_","VARCHAR(300)","Property value stored as a string."),
   ("REV_","INTEGER","Version number used for optimistic locking.")],[]),

T("ACT_GE_BYTEARRAY","General Table",1,"Stores binary data for deployments, variables, and exception stacks.",
  "Created when deployments, serialized variables, or error details need binary storage.",
  "Updated when binary content or metadata changes.",
  "Removed when parent deployment, variable, or job reference is deleted.","ID_",
  "ACT_RE_DEPLOYMENT, ACT_RU_VARIABLE, ACT_RU_JOB, ACT_RU_EXT_TASK",
  "Referenced by deployments, variables, jobs, and external tasks for binary content.",
  [("Deployment Resources","Stores BPMN, DMN, and form files."),
   ("Serialized Variables","Holds byte array values for object variables."),
   ("Error Diagnostics","Stores exception stack traces."),
   ("History Cleanup","REMOVAL_TIME_ supports time-based cleanup.")],
  [("ID_","VARCHAR(64)","Unique identifier of the byte array record."),
   ("REV_","INTEGER","Version number used for optimistic locking."),
   ("NAME_","VARCHAR(255)","Descriptive name of the stored binary resource."),
   ("DEPLOYMENT_ID_","VARCHAR(64)","References the deployment that owns this resource."),
   ("BYTES_","BYTEA","Raw binary content of the stored data."),
   ("GENERATED_","BOOLEAN","Indicates whether the content was engine-generated."),
   ("TENANT_ID_","VARCHAR(64)","Tenant identifier in a multi-tenant environment."),
   ("TYPE_","INTEGER","Internal type code classifying the byte array usage."),
   ("CREATE_TIME_","TIMESTAMP","Date and time when the byte array was created."),
   ("ROOT_PROC_INST_ID_","VARCHAR(64)","Root process instance for history cleanup correlation."),
   ("REMOVAL_TIME_","TIMESTAMP","Scheduled removal time for history cleanup.")],
  [("ACT_RE_DEPLOYMENT","ACT_GE_BYTEARRAY","Deployment resources are stored as byte arrays."),
   ("ACT_RU_VARIABLE","ACT_GE_BYTEARRAY","Serialized variable values reference byte arrays."),
   ("ACT_RU_JOB","ACT_GE_BYTEARRAY","Failed job exception stacks reference byte arrays.")]),

T("ACT_GE_SCHEMA_LOG","General Table",1,"Maintains an audit log of database schema version upgrades.",
  "Inserted on initial database creation and after each schema upgrade script.",
  "Not updated; entries are append-only.","Not deleted under normal operations.","ID_","—",
  "Standalone audit table tracking schema migration history.",
  [("Schema Audit","Records each schema version applied."),
   ("Upgrade Verification","DBAs verify which upgrade scripts ran."),
   ("Troubleshooting","Identifies schema version mismatches.")],
  [("ID_","VARCHAR(64)","Unique identifier of the schema log entry."),
   ("TIMESTAMP_","TIMESTAMP","Date and time when the schema change was applied."),
   ("VERSION_","VARCHAR(255)","Camunda schema version applied in this upgrade step.")],[]),

T("ACT_RE_DEPLOYMENT","Repository Table",2,"Stores deployment metadata for process, case, DMN, and form resources.",
  "Created when a new deployment is submitted via API or auto-deployment.",
  "Rarely updated after creation.","Deleted when the deployment and all definitions are removed.","ID_",
  "ACT_RE_PROCDEF, ACT_RE_CASE_DEF, ACT_RE_DECISION_DEF, ACT_GE_BYTEARRAY",
  "Parent container for all deployed definitions and their binary resources.",
  [("Process Deployment","Registers BPMN process deployments."),
   ("Resource Management","Groups definitions deployed together."),
   ("Tenant Isolation","Associates deployments with a specific tenant.")],
  [("ID_","VARCHAR(64)","Unique identifier of the deployment."),
   ("NAME_","VARCHAR(255)","Human-readable deployment name."),
   ("DEPLOY_TIME_","TIMESTAMP","Date and time when the deployment was created."),
   ("SOURCE_","VARCHAR(255)","Source system that created the deployment."),
   ("TENANT_ID_","VARCHAR(64)","Tenant identifier in a multi-tenant environment.")],
  [("ACT_RE_DEPLOYMENT","ACT_RE_PROCDEF","One deployment contains one or more process definitions."),
   ("ACT_RE_DEPLOYMENT","ACT_GE_BYTEARRAY","Deployment binary resources are stored in byte arrays.")]),

T("ACT_RE_PROCDEF","Repository Table",2,"Stores deployed BPMN process definition metadata for all versions.",
  "Created when a BPMN process is deployed.","Updated when suspension state or revision changes.",
  "Deleted when the parent deployment is removed.","ID_",
  "ACT_RE_DEPLOYMENT, ACT_RU_EXECUTION, ACT_RU_TASK, ACT_HI_PROCINST",
  "Central definition table referenced by all running and historic process instances.",
  [("Process Versioning","Tracks versioned process definitions by key."),
   ("Process Start","Provides metadata to start new process instances."),
   ("Suspension Control","Manages suspension state of a process definition."),
   ("History TTL","Defines history time-to-live for cleanup policies.")],
  [("ID_","VARCHAR(64)","Unique identifier of the process definition."),
   ("REV_","INTEGER","Version number used for optimistic locking."),
   ("CATEGORY_","VARCHAR(255)","Category label for grouping process definitions."),
   ("NAME_","VARCHAR(255)","Human-readable name of the process definition."),
   ("KEY_","VARCHAR(255)","Business key identifying the process across versions."),
   ("VERSION_","INTEGER","Version number incremented on each deployment of the same key."),
   ("DEPLOYMENT_ID_","VARCHAR(64)","References the deployment containing this definition."),
   ("RESOURCE_NAME_","VARCHAR(4000)","Classpath or filename of the BPMN resource."),
   ("DGRM_RESOURCE_NAME_","VARCHAR(4000)","Filename of the process diagram image resource."),
   ("HAS_START_FORM_KEY_","BOOLEAN","Indicates whether a start form is configured."),
   ("SUSPENSION_STATE_","INTEGER","Suspension state: 1=active, 2=suspended."),
   ("TENANT_ID_","VARCHAR(64)","Tenant identifier in a multi-tenant environment."),
   ("VERSION_TAG_","VARCHAR(64)","Optional version tag for semantic versioning."),
   ("HISTORY_TTL_","INTEGER","History time-to-live in days for cleanup."),
   ("STARTABLE_","BOOLEAN","Indicates whether the process can be started via API.")],
  [("ACT_RE_DEPLOYMENT","ACT_RE_PROCDEF","Deployment contains process definitions."),
   ("ACT_RE_PROCDEF","ACT_RU_EXECUTION","Running executions reference their process definition.")]),

T("ACT_RE_CAMFORMDEF","Repository Table",2,"Stores deployed Camunda form definition metadata.",
  "Created when a Camunda form is deployed.","Updated when revision changes.",
  "Deleted when the parent deployment is removed.","ID_","ACT_RE_DEPLOYMENT",
  "Form definitions deployed alongside or independently of process definitions.",
  [("Form Deployment","Registers embedded Camunda form definitions."),
   ("Form Versioning","Tracks versioned forms by key."),
   ("Task Forms","Provides form metadata for user task rendering.")],
  [("ID_","VARCHAR(64)","Unique identifier of the form definition."),
   ("REV_","INTEGER","Version number used for optimistic locking."),
   ("KEY_","VARCHAR(255)","Business key identifying the form across versions."),
   ("VERSION_","INTEGER","Version number incremented on each deployment of the same key."),
   ("DEPLOYMENT_ID_","VARCHAR(64)","References the deployment containing this form."),
   ("RESOURCE_NAME_","VARCHAR(4000)","Classpath or filename of the form resource."),
   ("TENANT_ID_","VARCHAR(64)","Tenant identifier in a multi-tenant environment.")],
  [("ACT_RE_DEPLOYMENT","ACT_RE_CAMFORMDEF","Deployment may contain Camunda form definitions.")]),

T("ACT_RE_CASE_DEF","Repository Table",2,"Stores deployed CMMN case definition metadata.",
  "Created when a CMMN case model is deployed.","Updated when revision changes.",
  "Deleted when the parent deployment is removed.","ID_",
  "ACT_RE_DEPLOYMENT, ACT_RU_CASE_EXECUTION, ACT_HI_CASEINST",
  "Case definitions are referenced by runtime and historic case instances.",
  [("Case Deployment","Registers CMMN case definitions."),
   ("Case Versioning","Tracks versioned case definitions by key."),
   ("Case Start","Provides metadata to start new case instances.")],
  [("ID_","VARCHAR(64)","Unique identifier of the case definition."),
   ("REV_","INTEGER","Version number used for optimistic locking."),
   ("CATEGORY_","VARCHAR(255)","Category label for grouping case definitions."),
   ("NAME_","VARCHAR(255)","Human-readable name of the case definition."),
   ("KEY_","VARCHAR(255)","Business key identifying the case across versions."),
   ("VERSION_","INTEGER","Version number incremented on each deployment of the same key."),
   ("DEPLOYMENT_ID_","VARCHAR(64)","References the deployment containing this definition."),
   ("RESOURCE_NAME_","VARCHAR(4000)","Classpath or filename of the CMMN resource."),
   ("DGRM_RESOURCE_NAME_","VARCHAR(4000)","Filename of the case diagram image resource."),
   ("TENANT_ID_","VARCHAR(64)","Tenant identifier in a multi-tenant environment."),
   ("HISTORY_TTL_","INTEGER","History time-to-live in days for cleanup.")],
  [("ACT_RE_DEPLOYMENT","ACT_RE_CASE_DEF","Deployment may contain CMMN case definitions."),
   ("ACT_RE_CASE_DEF","ACT_RU_CASE_EXECUTION","Case executions reference their case definition.")]),

T("ACT_RE_DECISION_DEF","Repository Table",2,"Stores deployed DMN decision definition metadata.",
  "Created when a DMN decision is deployed.","Updated when revision changes.",
  "Deleted when the parent deployment is removed.","ID_",
  "ACT_RE_DEPLOYMENT, ACT_RE_DECISION_REQ_DEF, ACT_HI_DECINST",
  "Decision definitions are evaluated at runtime and logged to history.",
  [("DMN Deployment","Registers DMN decision definitions."),
   ("Decision Evaluation","Provides metadata for business rule execution."),
   ("DRD Linkage","Links decisions to their decision requirements definition.")],
  [("ID_","VARCHAR(64)","Unique identifier of the decision definition."),
   ("REV_","INTEGER","Version number used for optimistic locking."),
   ("CATEGORY_","VARCHAR(255)","Category label for grouping decision definitions."),
   ("NAME_","VARCHAR(255)","Human-readable name of the decision definition."),
   ("KEY_","VARCHAR(255)","Business key identifying the decision across versions."),
   ("VERSION_","INTEGER","Version number incremented on each deployment of the same key."),
   ("DEPLOYMENT_ID_","VARCHAR(64)","References the deployment containing this definition."),
   ("RESOURCE_NAME_","VARCHAR(4000)","Classpath or filename of the DMN resource."),
   ("DGRM_RESOURCE_NAME_","VARCHAR(4000)","Filename of the decision diagram image resource."),
   ("DEC_REQ_ID_","VARCHAR(64)","References the parent decision requirements definition."),
   ("DEC_REQ_KEY_","VARCHAR(255)","Key of the parent decision requirements definition."),
   ("TENANT_ID_","VARCHAR(64)","Tenant identifier in a multi-tenant environment."),
   ("HISTORY_TTL_","INTEGER","History time-to-live in days for cleanup."),
   ("VERSION_TAG_","VARCHAR(64)","Optional version tag for semantic versioning.")],
  [("ACT_RE_DECISION_REQ_DEF","ACT_RE_DECISION_DEF","DRD contains one or more decision definitions."),
   ("ACT_RE_DECISION_DEF","ACT_HI_DECINST","Decision evaluations create historic decision instances.")]),

T("ACT_RE_DECISION_REQ_DEF","Repository Table",2,"Stores deployed DMN Decision Requirements Diagram (DRD) metadata.",
  "Created when a DMN DRD resource is deployed.","Updated when revision changes.",
  "Deleted when the parent deployment is removed.","ID_",
  "ACT_RE_DEPLOYMENT, ACT_RE_DECISION_DEF",
  "Parent DRD definition grouping related DMN decision definitions.",
  [("DRD Deployment","Registers decision requirements diagrams."),
   ("Decision Grouping","Groups related decisions under a single DRD."),
   ("Version Management","Tracks versioned DRD definitions by key.")],
  [("ID_","VARCHAR(64)","Unique identifier of the decision requirements definition."),
   ("REV_","INTEGER","Version number used for optimistic locking."),
   ("CATEGORY_","VARCHAR(255)","Category label for grouping DRD definitions."),
   ("NAME_","VARCHAR(255)","Human-readable name of the DRD definition."),
   ("KEY_","VARCHAR(255)","Business key identifying the DRD across versions."),
   ("VERSION_","INTEGER","Version number incremented on each deployment of the same key."),
   ("DEPLOYMENT_ID_","VARCHAR(64)","References the deployment containing this definition."),
   ("RESOURCE_NAME_","VARCHAR(4000)","Classpath or filename of the DRD resource."),
   ("DGRM_RESOURCE_NAME_","VARCHAR(4000)","Filename of the DRD diagram image resource."),
   ("TENANT_ID_","VARCHAR(64)","Tenant identifier in a multi-tenant environment.")],
  [("ACT_RE_DECISION_REQ_DEF","ACT_RE_DECISION_DEF","DRD contains one or more decision definitions.")]),
]

# Continue in part 2 - append more tables via exec or separate file
exec(open(Path(__file__).parent / "_gen_db_ref_part2.py", encoding="utf-8").read())
